FROM scratch AS ctx
COPY build_files /

FROM ghcr.io/ublue-os/bazzite-gnome:stable AS bazzite-gnome-khg
RUN rm /usr/share/ublue-os/bazzite/flatpak/install
COPY system_files/shared /
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh && \

    ostree container commit

RUN bootc container lint
